[package]
name = "terrarium"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { version = "1", features = ["derive"] }
eframe = { version = "0.36", default-features = false, features = [
  "default_fonts",
  "wayland",
  "wgpu",
  "x11",
], optional = true }
env_logger = "0.11"
glam = "0.33"
image = { version = "0.25" }
log = "0.4"
pollster = "1"
serde = "1"
serde_json = "1"
slotmap = "1"
thiserror = "2"
web-time = "1"
wgpu = "30"
winit = "0.30"

[features]
default = ["eframe"]
eframe = ["dep:eframe"]
