[package]
name = "terrarium"
version = "0.1.0"
edition = "2024"

[features]
default = ["meshpart", "physics", "default-skybox", "default-fonts", "eframe-default-fonts"]
meshpart = ["dep:gltf"]
physics = ["dep:rapier3d"]
default-skybox = []
default-fonts = []
eframe-default-fonts = ["eframe/default_fonts"]

[dependencies]
bytemuck = { version = "1", features = ["derive"] }
eframe = { version = "0.36", default-features = false, features = ["wayland", "wgpu", "x11"] }
env_logger = "0.11"
glam = "0.33"
gltf = { version = "1", optional = true }
image = { version = "0.25" }
log = "0.4"
rapier3d = { version = "0.35", optional = true }
serde = "1"
serde_json = "1"
slotmap = "1"
thiserror = "2"
web-time = "1"
wgpu = "30"
winit = "0.30"

[dev-dependencies]
bevy_app = "0.19"
bevy_ecs = "0.19"
bevy_state = "0.19"
bevy_tasks = "0.19"
bevy_time = "0.19"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
pollster = "1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["Document", "Element", "HtmlCanvasElement", "Window"] }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
getrandom = { version = "0.4", features = ["wasm_js"] }

[[example]]
name = "gltf"
required-features = ["meshpart"]

[[example]]
name = "physics"
required-features = ["physics"]

[[test]]
name = "gpu"
required-features = ["meshpart"]
