[package]
name = "terrarium"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { version = "1", features = ["derive"] }
eframe = { version = "0.36", default-features = false, features = [
  "default_fonts",
  "wayland",
  "wgpu",
  "x11",
] }
env_logger = "0.11"
glam = "0.33"
image = { version = "0.25" }
log = "0.4"
serde = "1"
serde_json = "1"
slotmap = "1"
thiserror = "2"
web-time = "1"
wgpu = "30"
winit = "0.30"

[target."wasm32-unknown-unknown".dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["Document", "Element", "HtmlCanvasElement", "Window"] }

[target."wasm32-unknown-unknown".dev-dependencies]
console_error_panic_hook = "0.1"
getrandom = { version = "0.4", features = ["wasm_js"] }
