[tools]
clang = "latest"
"github:Unreal-Works/cmdshim" = "latest"
"github:rust-cross/cargo-xwin" = "latest"
"github:trunk-rs/trunk" = "latest"
"github:wasm-bindgen/wasm-pack" = "latest"
lefthook = "latest"
oxfmt = "latest"
rust = { version = "nightly-2026-03-12", components = ["clippy", "rustfmt", "rust-src"] }

[hooks]
postinstall = ["lefthook install"]

[tasks.check]
description = "Run all linting and formatting checks"
depends = ["lint"]
run = "mise format:cargo --check && mise format:oxfmt --check"

[tasks.format]
description = "Format .rs/.toml/.yml"
depends = ["format:cargo", "format:oxfmt"]

[tasks."format:cargo"]
description = "Format .rs"
run = "cargo fmt --all"

[tasks."format:oxfmt"]
description = "Format .toml/.yml"
run = "oxfmt"

[tasks.lint]
description = "Lint .rs"
run = "cargo clippy --all-targets --all-features --workspace -- -D warnings"

[tasks.test]
description = "Run .rs tests"
run = "cargo test --all-targets --all-features"

[tasks."bench:native"]
description = "Run benchmarks for native"
run = "cargo bench --benches"

[tasks."serve:examples:app"]
description = "Serve the example app with Trunk"
dir = "{{config_root}}"
run = "trunk serve --config examples/Trunk.app.toml"

[tasks."run:examples:app"]
description = "Run the example app natively"
dir = "{{config_root}}"
run = "cargo run --example app"

[tasks."wsl:examples:app"]
description = "Run the example app in WSL"
dir = "{{config_root}}"
env = { CARGO_TARGET_X86_64_PC_WINDOWS_MSVC_RUNNER = "/usr/bin/env" }
run = "cargo xwin run --example app --target x86_64-pc-windows-msvc"

[env]
_.path = { path = ["{{ exec(command='cmdshim path') }}"], tools = true }

[_.cmdshim.terrarium]
run = [
  "cargo",
  "run",
  "--quiet",
  "--manifest-path",
  "{{config_root}}/Cargo.toml",
  "--all-features",
  "--",
]
