[tools]
"github:wasm-bindgen/wasm-pack" = "latest"
"npm:wrangler" = "latest"
oxfmt = "latest"
oxlint = "latest"
rust = { version = "nightly-2026-03-12", components = ["clippy", "rustfmt", "rust-src"] }
watchexec = "latest"

[tasks.dev]
run = "watchexec -e rs,html,css,scss -- trunk build"
